### PR TITLE
added a completed version of the linopy workshop on 16/12/2023

### PR DESCRIPTION
**Pull request by wehuang16**
I added a first draft (unfinished version) of the linopy workshop ipynb file. This is still work in progress so feel free to delay merging to main branch for now

### CODE REVIEW

**Comment by fneum** [comment]
Thanks! Let me know when the version is finished and I’ll have a look.

**Comment by pz-max** [comment]
Related to issue. https://github.com/fneum/data-science-for-esm/issues/5
@fneum , I talked with @wehuang16 before the PR was created.
We can take care of the first round of review :+1:

**Comment by pz-max** [comment]
Add a [PR](https://github.com/wehuang16/data-science-for-esm/pull/5) with small fixes/changes at @wehuang16 fork. If it's merged it shows up here. I really liked the comprehensiveness of Linopy compared to Pyomo.

**Comment by wehuang16** [comment]
@fneum @pz-max I believe the "14 linopy workshop ipynb file" is completed, and this pull request is ready to be merged:)

**Comment by fneum** [comment]
Really excellent! I made some modification, but this was really good and much easier to go through then `pyomo`.

**Pull request merged**
