### PR TITLE
Update 12-workshop-pypsa-sector-coupling.ipynb

### PR DESCRIPTION
**Pull request by pz-max**
just remove minor duplication

### CODE REVIEW

**Review by fneum — CHANGES_REQUESTED** [review]
I guess the deletion of atlite was not intended? Otherwise, looks good.

**Comment by pz-max** [comment]
The pre-commit is just cleaning/emptying all notebooks outputs. I didn't delete Atlite. I guess just a lot cells are cleaned.

See my commit on the effective changes (before the pre commit hits) 👍🏽

**Comment by fneum** [comment]
Ah, I see. Looked suspicious.

**Comment by pz-max** [comment]
[celebrate]     Maximilian Parzen reacted to your message:
________________________________

**Pull request merged**
